import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { useLongformArticles } from '@/hooks/useLongformArticles';
import { useNotes } from '@/hooks/useNotes';
import { useNostr } from '@nostrify/react';
import { useQuery } from '@tanstack/react-query';
import { NOSTR_CONFIG } from '@/config/nostr';
import { extractArticleMetadata } from '@/hooks/useLongformArticles';
